export const ApplicationHistory = [
  {
    reference: "SDKJVHF9876003",
    firstName: "John",
    lastName: "Doe",
    birthPlace: "KHMH",
    birthDistrict: "Belize",
    birthDate: "1999-10-01",
    registrationDate: "1999-10-02",
    age: 19,
    momFirstName: "Paulette",
    momLastName: "Doe",
    momMaidenName: "",
    momBirthCountry: "Belize",
    momBirthDate: "1880-03-06",
    momIdType: "Social Security",
    momIdNumber: "360000234",
    dadFirstName: "Jerry",
    dadLastName: "Doe",
    dadBirthCountry: "Belize",
    dadBirthDate: "1878-05-12",
    dadIdType: "Passport",
    dadIdNumber: "P123456",
    appFirstName: "Jenny",
    appLastName: "Doe",
    appAddressLn1: "123",
    appAddressLn2: "Bird Lane",
    appCity: "Belize City",
    appDistrict: "Belize",
    appCountry: "Belize",
    appIdType: "Social Security",
    appIdNumber: "380360320",
    appRelation: "Cousin",
    appPurpose: "Travel Abroad",
    appDate: "2018-11-10",
    delFirstName: "Jeffery",
    delLastName: "Doe",
    delIdType: "Passport",
    delIdNumber: "360000234",
    delTelephone: "+501-610-1234",
    delDateReceived: "2018-11-12",
    applicationStatus: "Submitted"
  },
  {
    reference: "SDKJVHF9876002",
    firstName: "Kim",
    lastName: "Peters",
    birthPlace: "KHMH",
    birthDistrict: "Belize",
    birthDate: "1999-10-01",
    registrationDate: "1999-10-02",
    age: 19,
    momFirstName: "Paulette",
    momLastName: "Peters",
    momMaidenName: "",
    momBirthCountry: "Belize",
    momBirthDate: "1880-03-06",
    momIdType: "Social Security",
    momIdNumber: "360000234",
    dadFirstName: "Jerry",
    dadLastName: "Peters",
    dadBirthCountry: "Belize",
    dadBirthDate: "1878-05-12",
    dadIdType: "Passport",
    dadIdNumber: "P123456",
    appFirstName: "Jenny",
    appLastName: "Peters",
    appAddressLn1: "123",
    appAddressLn2: "Bird Lane",
    appCity: "Belize City",
    appDistrict: "Belize",
    appCountry: "Belize",
    appIdType: "Social Security",
    appIdNumber: "380360320",
    appRelation: "Cousin",
    appPurpose: "Travel Abroad",
    appDate: "2018-10-01",
    delFirstName: "Jeffery",
    delLastName: "Peters",
    delIdType: "Passport",
    delIdNumber: "360000234",
    delTelephone: "+501-610-1234",
    delDateReceived: "2018-11-12",
    applicationStatus: "Approved"
  },
  {
    reference: "SDKJVHF9876001",
    firstName: "Sam",
    lastName: "Doe",
    birthPlace: "KHMH",
    birthDistrict: "Belize",
    birthDate: "1999-10-01",
    registrationDate: "1999-10-02",
    age: 19,
    momFirstName: "Paulette",
    momLastName: "Doe",
    momMaidenName: "",
    momBirthCountry: "Belize",
    momBirthDate: "1880-03-06",
    momIdType: "Social Security",
    momIdNumber: "360000234",
    dadFirstName: "Jerry",
    dadLastName: "Doe",
    dadBirthCountry: "Belize",
    dadBirthDate: "1878-05-12",
    dadIdType: "Passport",
    dadIdNumber: "P123456",
    appFirstName: "Jenny",
    appLastName: "Doe",
    appAddressLn1: "123",
    appAddressLn2: "Bird Lane",
    appCity: "Belize City",
    appDistrict: "Belize",
    appCountry: "Belize",
    appIdType: "Social Security",
    appIdNumber: "380360320",
    appRelation: "Cousin",
    appPurpose: "Travel Abroad",
    appDate: "2018-09-15",
    delFirstName: "Jeffery",
    delLastName: "Doe",
    delIdType: "Passport",
    delIdNumber: "360000234",
    delTelephone: "+501-610-1234",
    delDateReceived: "2018-11-12",
    applicationStatus: "Approved"
  }
];
